### ISSUE TITLE
Few Additional Feature Request

### ISSUE THREAD

**Issue by messagebeliever2022** [Aveek-Saha/DuskPlayer#69]
1. An option or menu to add Likes Or Favourites Songs.. It has to been displayed with favourite icon?

![image](https://user-images.githubusercontent.com/112235944/193464336-485c0bf4-3fe9-415a-9a6b-befffe9d1896.png)

2. Can the app be made as portable as well ? like other https://portableapps.com/

Is it possible to carry the app and music in pen drive and play in any computer?

3. I have many files in .rm and .ram format (real media player formats). Is it possible to provide support for .rm and .ram files 

4. Need an option to synchronize lyrics with an audio file.

**Comment by Aveek-Saha** [comment]
1. and 4 are outside the scope of this project since it's intended to be a minimal music player.

As for 3. Howler. the audio library DuskPlayer uses under the hood does not support .rm and .ram formats so it isn't possible to support them.

For 2. this is possible and can be looked into, please open an issue with the appropriate template.
